-- The customer-support schema the postgres MCP resource server reads and writes.
--
-- Schema only. The rows the scenarios run against come from the W12 seeder, so
-- a clean volume has the tables and no data. Postgres runs this file once, from
-- /docker-entrypoint-initdb.d, and only when the data directory is empty, which
-- is what `make reset` produces.
--
-- The ids are identity columns generated by default rather than always, so a
-- seeder can insert its own stable ids and a server-side insert can leave the
-- id out. A seeder that inserts explicit ids has to advance each sequence
-- afterwards (`setval(pg_get_serial_sequence('customers', 'id'), (select
-- max(id) from customers))`, and the same for the other three), or a later
-- default insert reuses a low id and collides once it reaches the seeded range.
-- `notes.author_login` is the verified caller's subject; W8 does not map it to a
-- human-readable login.

CREATE TABLE customers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    email text NOT NULL,
    owner_login text NOT NULL
);

CREATE TABLE tickets (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id integer NOT NULL REFERENCES customers (id),
    subject text NOT NULL,
    body text NOT NULL,
    author_email text NOT NULL,
    status text NOT NULL,
    incident_id text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE api_keys (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id integer NOT NULL REFERENCES customers (id),
    key_value text NOT NULL,
    label text NOT NULL,
    revoked boolean NOT NULL DEFAULT false
);

CREATE TABLE notes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id integer NOT NULL REFERENCES tickets (id),
    author_login text NOT NULL,
    body text NOT NULL
);
